import { StateProps as ListStateProps, DispatchProps as ListDispatchProps } from './List';

export interface IProps extends ListStateProps, ListDispatchProps {
  initialize?: Function;
  getFEATURE_NAME_UPPER_CAMEL?: Function;
  getFEATURE_NAME_UPPER_CAMELList?: Function;
  addFEATURE_NAME_UPPER_CAMEL?: Function;
  updateFEATURE_NAME_UPPER_CAMEL?: Function;
  deleteFEATURE_NAME_UPPER_CAMEL?: Function;
}

export const FEATURE_NAME_CAPITAL_TYPES = {
  GET_FEATURE_NAME_CAPITAL: 'GET_FEATURE_NAME_CAPITAL',
  GET_FEATURE_NAME_CAPITAL_LIST: 'GET_FEATURE_NAME_CAPITAL_LIST',
  ADD_FEATURE_NAME_CAPITAL: 'ADD_FEATURE_NAME_CAPITAL',
  UPDATE_FEATURE_NAME_CAPITAL: 'UPDATE_FEATURE_NAME_CAPITAL',
  DELETE_FEATURE_NAME_CAPITAL: 'DELETE_FEATURE_NAME_CAPITAL',
};
